# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Giornetta < Formula
  desc "CLI for managing Civo resources."
  homepage "https://github.com/giornetta/cli"
  version "1.4.8-rc4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc4/civo-1.4.8-rc4-darwin-amd64.tar.gz"
      sha256 "fafb0e6d3f03603b18c8ca1173f2a7be42d4941c20e97e00d165e41589f20485"

      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc4/civo-1.4.8-rc4-darwin-arm64.tar.gz"
      sha256 "56bf3619113012f39b9fb133b42e9c606e922f6e9251e570dc313cf738bd3c86"

      def install
        bin.install "civo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc4/civo-1.4.8-rc4-linux-amd64.tar.gz"
      sha256 "3329fc07d0de0cf9d0e7430cc838c3c6f3d370871f0093db3ad6f237e62e9378"
      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc4/civo-1.4.8-rc4-linux-arm.tar.gz"
      sha256 "67c83b8cfddb67d66bca20bf90375411b5d592f8caba3bca7d9de7ada59a52a3"
      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc4/civo-1.4.8-rc4-linux-arm64.tar.gz"
      sha256 "d7053d6e88c9414d3e0a85b0045caff1f5c10ca9aa94085695966fb63fcc6616"
      def install
        bin.install "civo"
      end
    end
  end
end
