# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Giornetta < Formula
  desc "CLI for managing Civo resources."
  homepage "https://github.com/giornetta/cli"
  version "1.4.8-rc4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc4/civo-1.4.8-rc4-darwin-amd64.tar.gz"
      sha256 "b8bc507bece9ee6656ae505587be7c1568449c467989e2d9c13cd99efa36226d"

      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc4/civo-1.4.8-rc4-darwin-arm64.tar.gz"
      sha256 "2b11a98478925cfaf02f652f5f39353c99f0b033b758bc75b12caac158386d71"

      def install
        bin.install "civo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc4/civo-1.4.8-rc4-linux-amd64.tar.gz"
      sha256 "4b84647ad487e99da9526f5d7e84c9e28237696a12947b10e45aa605bf5a4770"
      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc4/civo-1.4.8-rc4-linux-arm.tar.gz"
      sha256 "9342d662a4cc4b81243770c783c20ff84a2b05fa12589966117cc558e67ecbc7"
      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc4/civo-1.4.8-rc4-linux-arm64.tar.gz"
      sha256 "91524bb264b5f2cfb0afde4e05709fc3f1ee7af59fd8794722e6339e56be9ef1"
      def install
        bin.install "civo"
      end
    end
  end
end
