# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Giornetta < Formula
  desc "CLI for managing Civo resources."
  homepage "https://github.com/giornetta/cli"
  version "1.4.8-rc5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc5/civo-1.4.8-rc5-darwin-amd64.tar.gz"
      sha256 "b396481e0f7946c736ac5e51bdd96fc7c76640e8429372a2c8e65f52f9d6ba4b"

      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc5/civo-1.4.8-rc5-darwin-arm64.tar.gz"
      sha256 "dc8e6b8ddb9a2d0f1c521dc1834bb6aca8507c697973de5b7f49ae41f76dd3bb"

      def install
        bin.install "civo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc5/civo-1.4.8-rc5-linux-amd64.tar.gz"
      sha256 "66f09993bb9ae3e0e660499130dddf0d6e55a3b22b15b14df4c53d2a4e4a9ff3"
      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc5/civo-1.4.8-rc5-linux-arm.tar.gz"
      sha256 "e7902646b4e629fc3be28241bdd8889df155af65901b035640e428ff57328b05"
      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/giornetta/cli/releases/download/v1.4.8-rc5/civo-1.4.8-rc5-linux-arm64.tar.gz"
      sha256 "01113a42f35ce077515afa89a0391edc434467ca4d17238941183a9cc10d9715"
      def install
        bin.install "civo"
      end
    end
  end
end
